# Generated by Django 3.0.1 on 2020-01-05 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='passrd',
            new_name='password',
        ),
    ]
