# Generated by Django 3.0.1 on 2020-01-05 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_auto_20200103_0657'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
