# Generated by Django 3.0.1 on 2020-01-02 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='Picture',
        ),
    ]
